import { defineConfig } from "oxlint";

export default defineConfig({
  categories: {
    correctness: "error",
    pedantic: "warn",
    perf: "warn",
    nursery: "warn",
    suspicious: "warn",
    restriction: "warn",
  },
  env: {
    vitest: true,
    jest: true,
    es2024: true,
    node: true,
    browser: true,
  },
  ignorePatterns: ["node_modules/", "out/"],
  jsPlugins: [
    "eslint-plugin-regexp",
    {
      name: "legibility",
      specifier: "eslint-plugin-legibility",
    },
  ],
  options: {
    reportUnusedDisableDirectives: "warn",
    respectEslintDisableDirectives: true,
    typeAware: true,
    typeCheck: true,
  },
  plugins: ["typescript", "eslint", "oxc", "jsdoc", "unicorn", "node", "promise", "import"],
  rules: {
    "constructor-super": "error",
    "eslint/accessor-pairs": "warn",
    "eslint/array-callback-return": "warn",
    "eslint/eqeqeq": "warn",
    "eslint/max-classes-per-file": "warn",
    "eslint/max-depth": "warn",
    "eslint/max-lines": "off",
    "eslint/max-lines-per-function": "off",
    "eslint/max-nested-callbacks": "warn",
    "eslint/no-array-constructor": "warn",
    "eslint/no-case-declarations": "warn",
    "eslint/no-constructor-return": "warn",
    "eslint/no-else-return": "warn",
    "eslint/no-fallthrough": "warn",
    "eslint/no-inline-comments": "warn",
    "eslint/no-inner-declarations": "warn",
    "eslint/no-lonely-if": "warn",
    "eslint/no-loop-func": "warn",
    "eslint/no-negated-condition": "off",
    "eslint/no-new-wrappers": "warn",
    "eslint/no-object-constructor": "warn",
    "eslint/no-promise-executor-return": "warn",
    "eslint/no-prototype-builtins": "warn",
    "eslint/no-redeclare": ["warn", { builtinGlobals: true }],
    "eslint/no-self-compare": "warn",
    "eslint/no-shadow": ["warn", { hoist: "all", builtinGlobals: false }],
    "eslint/no-throw-literal": "warn",
    "eslint/no-useless-return": "warn",
    "eslint/no-warning-comments": "warn",
    "eslint/prefer-promise-reject-errors": "warn",
    "eslint/radix": "warn",
    "eslint/require-await": "warn",
    "eslint/require-unicode-regexp": "off",
    "eslint/sort-vars": "warn",
    "eslint/symbol-description": "warn",
    "for-direction": "error",
    "getter-return": "error",
    "import/max-dependencies": "off",
    "import/no-cycle": [
      "error",
      {
        maxDepth: 2,
      },
    ],
    "jsdoc/require-param": "off",
    "jsdoc/require-param-description": "warn",
    "jsdoc/require-param-name": "warn",
    "jsdoc/require-param-type": "warn",
    "jsdoc/require-returns": "off",
    "jsdoc/require-returns-description": "warn",
    "jsdoc/require-returns-type": "warn",
    "jsdoc/require-throws-type": "warn",
    "jsdoc/require-yields-type": "warn",
    "import/no-unassigned-import": [
      "warn",
      {
        allow: ["**/*.css"],
      },
    ],
    "legibility/hoist-if-operators": ["warn", { max: 1 }],
    "legibility/max-array-chain-depth": ["warn", { max: 2 }],
    "legibility/max-control-flow-depth": ["warn", { max: 4 }],
    "legibility/max-expression-operators": ["warn", { max: 7 }],
    "legibility/max-function-parameters": ["warn", { max: 5 }],
    "legibility/no-automated-comment-attribution": "off",
    "legibility/no-complex-ternaries": "off",
    "legibility/no-computed-values": "off",
    "legibility/no-direct-node-bin-smoke": "warn",
    "legibility/no-hidden-side-effects": "warn",
    "legibility/no-identity-array-callback": "warn",
    "legibility/no-mixed-filename-casing": "warn",
    "legibility/no-quadratic-patterns": "warn",
    "legibility/no-redundant-boolean-logic": "warn",
    "legibility/no-redundant-nullish-fallback": "warn",
    "legibility/no-repeated-collection-search": "warn",
    "legibility/no-single-use-renaming-alias": "warn",
    "legibility/no-small-collection-conversion": "off",
    "legibility/no-stacked-comments": "off",
    "legibility/no-standalone-array-mutations": "off",
    "legibility/no-trivial-wrapper-functions": "warn",
    "legibility/no-unmatched-comments": "off",
    "legibility/no-unnecessary-async": "warn",
    "legibility/no-unnecessary-block-callback": "warn",
    "legibility/prefer-concat-object-assign": "off",
    "legibility/prefer-early-return": "warn",
    "legibility/prefer-flat-map": "warn",
    "legibility/prefer-guard-clauses": "warn",
    "legibility/prefer-object-lookup": "warn",
    "legibility/prefer-positive-condition-names": "warn",
    "legibility/require-executable-shebang": "warn",
    "legibility/require-filename-matches-dirname": "off",
    "legibility/require-jsdoc-multiline-comments": "off",
    "max-lines-per-function": "off",
    "no-array-constructor": "error",
    "no-case-declarations": "error",
    "no-class-assign": "error",
    "no-compare-neg-zero": "error",
    "no-cond-assign": "error",
    "no-const-assign": "error",
    "no-constant-binary-expression": "error",
    "no-constant-condition": "error",
    "no-control-regex": "error",
    "no-debugger": "error",
    "no-delete-var": "error",
    "no-dupe-class-members": "error",
    "no-dupe-else-if": "error",
    "no-dupe-keys": "error",
    "no-duplicate-case": "error",
    "no-empty": "error",
    "no-empty-character-class": "off",
    "no-empty-pattern": "error",
    "no-empty-static-block": "error",
    "no-ex-assign": "error",
    "no-extra-boolean-cast": "error",
    "no-fallthrough": "error",
    "no-func-assign": "error",
    "no-global-assign": "error",
    "no-import-assign": "error",
    "no-invalid-regexp": "off",
    "no-irregular-whitespace": "error",
    "no-loss-of-precision": "error",
    "no-misleading-character-class": "error",
    "no-new-native-nonconstructor": "error",
    "no-nonoctal-decimal-escape": "error",
    "no-obj-calls": "error",
    "no-proto": "error",
    "no-prototype-builtins": "warn",
    "no-regex-spaces": "error",
    "no-self-assign": "error",
    "no-setter-return": "error",
    "no-shadow-restricted-names": "error",
    "no-sparse-arrays": "error",
    "no-this-before-super": "error",
    "no-unassigned-vars": ["warn"],
    "no-undef": ["error"],
    "no-unexpected-multiline": "error",
    "no-unreachable": "error",
    "no-unsafe-finally": "error",
    "no-unsafe-negation": "error",
    "no-unsafe-optional-chaining": "error",
    "no-unused-expressions": ["warn"],
    "no-unused-labels": "error",
    "no-unused-private-class-members": "error",
    "no-unused-vars": [
      "warn",
      {
        args: "all",
        argsIgnorePattern: "^_",
        caughtErrors: "all",
        caughtErrorsIgnorePattern: "^_",
        destructuredArrayIgnorePattern: "^_",
        ignoreRestSiblings: true,
        varsIgnorePattern: "^_",
      },
    ],
    "no-useless-assignment": ["warn"],
    "no-useless-backreference": "off",
    "no-useless-catch": "error",
    "no-useless-constructor": "error",
    "no-useless-escape": "error",
    "no-var": ["warn"],
    "no-with": "error",
    "object-shorthand": [
      "warn",
      "always",
      {
        avoidQuotes: true,
        ignoreConstructors: false,
      },
    ],
    "oxc/branches-sharing-code": "warn",
    "prefer-arrow-callback": ["warn"],
    "prefer-const": ["warn"],
    "prefer-object-has-own": "warn",
    "prefer-regex-literals": "error",
    "prefer-spread": ["error"],
    "prefer-template": ["warn"],
    "preserve-caught-error": "error",
    "regexp/confusing-quantifier": "warn",
    "regexp/control-character-escape": "error",
    "regexp/match-any": "error",
    "regexp/negation": "error",
    "regexp/no-contradiction-with-assertion": "error",
    "regexp/no-dupe-characters-character-class": "error",
    "regexp/no-dupe-disjunctions": "error",
    "regexp/no-empty-alternative": "warn",
    "regexp/no-empty-capturing-group": "error",
    "regexp/no-empty-character-class": "error",
    "regexp/no-empty-group": "error",
    "regexp/no-empty-lookarounds-assertion": "error",
    "regexp/no-empty-string-literal": "error",
    "regexp/no-escape-backspace": "error",
    "regexp/no-extra-lookaround-assertions": "error",
    "regexp/no-invalid-regexp": "error",
    "regexp/no-invisible-character": "error",
    "regexp/no-lazy-ends": "warn",
    "regexp/no-legacy-features": "error",
    "regexp/no-misleading-capturing-group": "error",
    "regexp/no-misleading-unicode-character": "error",
    "regexp/no-missing-g-flag": "error",
    "regexp/no-non-standard-flag": "error",
    "regexp/no-obscure-range": "error",
    "regexp/no-optional-assertion": "error",
    "regexp/no-potentially-useless-backreference": "warn",
    "regexp/no-super-linear-backtracking": "error",
    "regexp/no-trivially-nested-assertion": "error",
    "regexp/no-trivially-nested-quantifier": "error",
    "regexp/no-unused-capturing-group": "error",
    "regexp/no-useless-assertions": "error",
    "regexp/no-useless-backreference": "error",
    "regexp/no-useless-character-class": "error",
    "regexp/no-useless-dollar-replacements": "error",
    "regexp/no-useless-escape": "error",
    "regexp/no-useless-flag": "warn",
    "regexp/no-useless-lazy": "error",
    "regexp/no-useless-non-capturing-group": "error",
    "regexp/no-useless-quantifier": "error",
    "regexp/no-useless-range": "error",
    "regexp/no-useless-set-operand": "error",
    "regexp/no-useless-string-literal": "error",
    "regexp/no-useless-two-nums-quantifier": "error",
    "regexp/no-zero-quantifier": "error",
    "regexp/optimal-lookaround-quantifier": "warn",
    "regexp/optimal-quantifier-concatenation": "error",
    "regexp/prefer-character-class": "error",
    "regexp/prefer-d": "error",
    "regexp/prefer-plus-quantifier": "error",
    "regexp/prefer-predefined-assertion": "error",
    "regexp/prefer-question-quantifier": "error",
    "regexp/prefer-range": "error",
    "regexp/prefer-set-operation": "error",
    "regexp/prefer-star-quantifier": "error",
    "regexp/prefer-unicode-codepoint-escapes": "error",
    "regexp/prefer-w": "error",
    "regexp/simplify-set-operations": "error",
    "regexp/sort-flags": "error",
    "regexp/strict": "error",
    "regexp/use-ignore-case": "error",
    "require-yield": "error",
    "typescript/adjacent-overload-signatures": "error",
    "typescript/array-type": "error",
    "typescript/await-thenable": "error",
    "typescript/ban-ts-comment": "off",
    "typescript/ban-tslint-comment": "error",
    "typescript/ban-types": "warn",
    "typescript/class-literal-property-style": "error",
    "typescript/consistent-generic-constructors": "error",
    "typescript/consistent-indexed-object-style": "error",
    "typescript/consistent-type-assertions": "error",
    "typescript/consistent-type-definitions": "warn",
    "typescript/no-array-delete": "error",
    "typescript/no-base-to-string": "error",
    "typescript/no-confusing-non-null-assertion": "error",
    "typescript/no-confusing-void-expression": "warn",
    "typescript/no-deprecated": "error",
    "typescript/no-duplicate-enum-values": "error",
    "typescript/no-duplicate-type-constituents": "error",
    "typescript/no-empty-object-type": "error",
    "typescript/no-explicit-any": "error",
    "typescript/no-extra-non-null-assertion": "error",
    "typescript/no-extraneous-class": "error",
    "typescript/no-for-in-array": "error",
    "typescript/no-implied-eval": "error",
    "typescript/no-invalid-void-type": "error",
    "typescript/no-meaningless-void-operator": "error",
    "typescript/no-misused-new": "error",
    "typescript/no-misused-promises": "warn",
    "typescript/no-misused-spread": "error",
    "typescript/no-mixed-enums": "error",
    "typescript/no-namespace": "error",
    "typescript/no-non-null-asserted-nullish-coalescing": "error",
    "typescript/no-non-null-asserted-optional-chain": "error",
    "typescript/no-non-null-assertion": "warn",
    "typescript/no-redundant-type-constituents": "error",
    "typescript/no-require-imports": "error",
    "typescript/no-unnecessary-boolean-literal-compare": "error",
    "typescript/no-unnecessary-template-expression": "warn",
    "typescript/no-unnecessary-type-assertion": "warn",
    "typescript/no-unnecessary-type-constraint": "error",
    "typescript/no-unnecessary-type-conversion": "error",
    "typescript/no-unnecessary-type-parameters": "error",
    "typescript/no-unsafe-argument": "warn",
    "typescript/no-unsafe-assignment": "warn",
    "typescript/no-unsafe-call": "warn",
    "typescript/no-unsafe-declaration-merging": "error",
    "typescript/no-unsafe-enum-comparison": "error",
    "typescript/no-unsafe-function-type": "error",
    "typescript/no-unsafe-member-access": "warn",
    "typescript/no-unsafe-return": "warn",
    "typescript/no-unsafe-unary-minus": "error",
    "typescript/no-useless-default-assignment": "error",
    "typescript/no-wrapper-object-types": "error",
    "typescript/non-nullable-type-assertion-style": "error",
    "typescript/only-throw-error": "error",
    "typescript/prefer-as-const": "error",
    "typescript/prefer-enum-initializers": "warn",
    "typescript/prefer-find": "error",
    "typescript/prefer-function-type": "error",
    "typescript/prefer-includes": "warn",
    "typescript/prefer-literal-enum-member": "error",
    "typescript/prefer-namespace-keyword": "error",
    "typescript/prefer-nullish-coalescing": "warn",
    "typescript/prefer-optional-chain": ["warn"],
    "typescript/prefer-promise-reject-errors": ["warn"],
    "typescript/prefer-readonly-parameter-types": "off",
    "typescript/prefer-reduce-type-parameter": "error",
    "typescript/prefer-return-this-type": "error",
    "typescript/prefer-string-starts-ends-with": [
      "warn",
      {
        allowSingleElementEquality: "always",
      },
    ],
    "typescript/prefer-ts-expect-error": "warn",
    "typescript/related-getter-setter-pairs": "error",
    "typescript/require-await": "warn",
    "typescript/restrict-plus-operands": "warn",
    "typescript/restrict-template-expressions": [
      "error",
      {
        allow: [
          {
            from: "lib",
            name: ["Error", "URL", "URLSearchParams", "Date"],
          },
        ],
        allowAny: true,
        allowBoolean: true,
        allowNullish: true,
        allowNumber: true,
        allowRegExp: true,
      },
    ],
    "typescript/return-await": ["error", "error-handling-correctness-only"],
    "typescript/strict-boolean-expressions": "error",
    "typescript/strict-void-return": "warn",
    "typescript/switch-exhaustiveness-check": "warn",
    "typescript/triple-slash-reference": "error",
    "typescript/unified-signatures": "error",
    "unicorn/consistent-assert": "warn",
    "unicorn/consistent-empty-array-spread": "warn",
    "unicorn/escape-case": "warn",
    "unicorn/explicit-length-check": "warn",
    "unicorn/new-for-builtins": "warn",
    "unicorn/no-array-callback-reference": "warn",
    "unicorn/no-hex-escape": "warn",
    "unicorn/no-immediate-mutation": "warn",
    "unicorn/no-instanceof-array": "warn",
    "unicorn/no-lonely-if": "warn",
    "unicorn/no-negated-condition": "off",
    "unicorn/no-negation-in-equality-check": "warn",
    "unicorn/no-new-array": "off",
    "unicorn/no-new-buffer": "warn",
    "unicorn/no-object-as-default-parameter": "warn",
    "unicorn/no-static-only-class": "warn",
    "unicorn/no-this-assignment": "warn",
    "unicorn/no-typeof-undefined": "warn",
    "unicorn/no-unnecessary-array-flat-depth": "warn",
    "unicorn/no-unnecessary-array-splice-count": "warn",
    "unicorn/no-unnecessary-slice-end": "warn",
    "unicorn/no-unreadable-iife": "warn",
    "unicorn/no-useless-promise-resolve-reject": "warn",
    "unicorn/no-useless-switch-case": "warn",
    "unicorn/no-useless-undefined": "warn",
    "unicorn/prefer-array-flat": "warn",
    "unicorn/prefer-array-some": "warn",
    "unicorn/prefer-at": "warn",
    "unicorn/prefer-blob-reading-methods": "warn",
    "unicorn/prefer-code-point": "warn",
    "unicorn/prefer-date-now": "warn",
    "unicorn/prefer-dom-node-append": "warn",
    "unicorn/prefer-dom-node-dataset": "warn",
    "unicorn/prefer-dom-node-remove": "warn",
    "unicorn/prefer-event-target": "warn",
    "unicorn/prefer-import-meta-properties": "warn",
    "unicorn/prefer-math-min-max": "warn",
    "unicorn/prefer-math-trunc": "warn",
    "unicorn/prefer-native-coercion-functions": "warn",
    "unicorn/prefer-number-coercion": "warn",
    "unicorn/prefer-prototype-methods": "warn",
    "unicorn/prefer-query-selector": "off",
    "unicorn/prefer-regexp-test": "warn",
    "unicorn/prefer-single-call": "warn",
    "unicorn/prefer-string-replace-all": "warn",
    "unicorn/prefer-string-slice": "warn",
    "unicorn/prefer-top-level-await": "warn",
    "unicorn/prefer-type-error": "warn",
    "unicorn/require-number-to-fixed-digits-argument": "warn",
    "use-isnan": "error",
    "valid-typeof": "error",
    "eslint/class-methods-use-this": "warn",
    "eslint/complexity": "off",
    "eslint/default-case": "warn",
    "eslint/no-alert": "warn",
    "eslint/no-bitwise": "off",
    "eslint/no-console": "off",
    "eslint/no-div-regex": "warn",
    "eslint/no-empty": "warn",
    "eslint/no-empty-function": "warn",
    "eslint/no-eq-null": "warn",
    "eslint/no-implicit-globals": "warn",
    "eslint/no-param-reassign": "warn",
    "eslint/no-plusplus": "off",
    "eslint/no-proto": "warn",
    "eslint/no-regex-spaces": "warn",
    "eslint/no-restricted-globals": "warn",
    "eslint/no-restricted-imports": "warn",
    "eslint/no-restricted-properties": "warn",
    "eslint/no-sequences": "warn",
    "eslint/no-undefined": "warn",
    "eslint/no-use-before-define": "error",
    "eslint/no-var": "warn",
    "eslint/no-void": "warn",
    "eslint/unicode-bom": "warn",
    "import/extensions": "warn",
    "import/no-amd": "warn",
    "import/no-commonjs": "warn",
    "import/no-default-export": "off",
    "import/no-dynamic-require": "warn",
    "import/no-relative-parent-imports": "warn",
    "import/no-webpack-loader-syntax": "warn",
    "import/unambiguous": "warn",
    "jsdoc/check-access": "warn",
    "jsdoc/empty-tags": "warn",
    "jsx_a11y/anchor-ambiguous-text": "warn",
    "node/handle-callback-err": "warn",
    "node/no-new-require": "warn",
    "node/no-path-concat": "warn",
    "node/no-process-env": "warn",
    "node/no-top-level-await": "warn",
    "oxc/bad-bitwise-operator": "warn",
    "oxc/no-async-await": "off",
    "oxc/no-barrel-file": "warn",
    "oxc/no-const-enum": "warn",
    "oxc/no-optional-chaining": "off",
    "oxc/no-rest-spread-properties": "off",
    "promise/catch-or-return": "warn",
    "promise/spec-only": "warn",
    "typescript/explicit-function-return-type": "warn",
    "typescript/explicit-member-accessibility": "warn",
    "typescript/explicit-module-boundary-types": "warn",
    "typescript/no-dynamic-delete": "warn",
    "typescript/no-import-type-side-effects": "warn",
    "typescript/no-restricted-types": "warn",
    "typescript/no-var-requires": "warn",
    "typescript/promise-function-async": "warn",
    "typescript/use-unknown-in-catch-callback-variable": "warn",
    "unicorn/import-style": "warn",
    "unicorn/no-abusive-eslint-disable": "warn",
    "unicorn/no-anonymous-default-export": "warn",
    "unicorn/no-array-for-each": "warn",
    "unicorn/no-array-reduce": "warn",
    "unicorn/no-document-cookie": "warn",
    "unicorn/no-length-as-slice-end": "warn",
    "unicorn/no-magic-array-flat-depth": "warn",
    "unicorn/no-process-exit": "warn",
    "unicorn/no-useless-error-capture-stack-trace": "warn",
    "unicorn/prefer-modern-math-apis": "warn",
    "unicorn/prefer-module": "warn",
    "unicorn/prefer-node-protocol": "warn",
    "unicorn/prefer-number-properties": "warn",
    "vitest/require-test-timeout": "warn",
  },
  settings: {
    jsdoc: {
      augmentsExtendsReplacesDocs: false,
      exemptDestructuredRootsFromChecks: false,
      ignoreInternal: false,
      ignorePrivate: false,
      ignoreReplacesDocs: true,
      implementsReplacesDocs: false,
      overrideReplacesDocs: true,
      tagNamePreference: {},
    },
  },
});
